src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
class Question
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(nullable: true)]

    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?User $id_user = null;
    /**
     * @Assert\NotBlank(message="champs obligatoire")
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $question = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_pub = null;

    #[ORM\Column(nullable: true)]
    private ?int $likes = null;



    #[ORM\Column(nullable: true)]
    private ?int $dislikes = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;
    public function getuser(): ?User
    {
        return $this->id_user;
    }

    public function setuser(?User $user): self
    {
        $this->id_user = $user;

        return $this;
    }

    #[ORM\Column(nullable: true)]
    private ?bool $hide_name = null;
    public function getId(): ?int
    {
        return $this->id;
    }


    public function __construct()
    {
        $this->date_pub = new \DateTime();
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getDatePub(): ?\DateTimeInterface
    {
        return $this->date_pub;
    }

    public function setDatePub(\DateTimeInterface $date_pub): self
    {
        $this->date_pub = $date_pub;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(?int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }
    public function incrementLikes(): void
    {
        ++$this->likes;
    }
    public function getDislikes(): ?int
    {
        return $this->dislikes;
    }
    public function incrementDislikes(): void
    {
        ++$this->dislikes;
    }

    public function setDislikes(?int $dislikes): self
    {
        $this->dislikes = $dislikes;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getHideName(): ?bool
    {
        return $this->hide_name;
    }

    public function setHideName(bool $hide_name): self
    {
        $this->hide_name = $hide_name;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups("user")]
    private ?string $nom = null;



    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]
    #[Groups("user")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]
    #[Groups("user")]
    private ?string $genre = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]
    #[Groups("user")]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Ce champ est obligatoire')]
    #[Groups("user")]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "Please, upload the photo.")]

    private $profilepicture;

    #[ORM\Column(type: 'boolean')]
    private $activate = true;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "mail is required")]
    #[Assert\Email(Message: "the email '{{ value }}' is not a valid mail")]
    #[Groups("user")]
    private ?string $email = null;

    #[ORM\Column]

    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'Patient', targetEntity: Fiche::class)]
    private Collection $fiches;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: RendezVous::class)]
    private Collection $rendezVouses;

    public function __construct()
    {

        $this->fiches = new ArrayCollection();
        $this->rendezVouses = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }
    public function getadresse(): ?string
    {
        return $this->adresse;
    }

    public function setadresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
    /**
     * @return Collection<int, Fiche>
     */
    public function getFiches(): Collection
    {
        return $this->fiches;
    }

    public function addFich(Fiche $fich): self
    {
        if (!$this->fiches->contains($fich)) {
            $this->fiches->add($fich);
            $fich->setPatient($this);
        }

        return $this;
    }

    public function removeFich(Fiche $fich): self
    {
        if ($this->fiches->removeElement($fich)) {
            // set the owning side to null (unless already changed)
            if ($fich->getPatient() === $this) {
                $fich->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RendezVous>
     */
    public function getRendezVouses(): Collection
    {
        return $this->rendezVouses;
    }

    public function addRendezVouse(RendezVous $rendezVouse): self
    {
        if (!$this->rendezVouses->contains($rendezVouse)) {
            $this->rendezVouses->add($rendezVouse);
            $rendezVouse->setPatient($this);
        }

        return $this;
    }

    public function removeRendezVouse(RendezVous $rendezVouse): self
    {
        if ($this->rendezVouses->removeElement($rendezVouse)) {
            // set the owning side to null (unless already changed)
            if ($rendezVouse->getPatient() === $this) {
                $rendezVouse->setPatient(null);
            }
        }

        return $this;
    }
    public function getprenom(): ?string
    {
        return $this->prenom;
    }
    public function getnom(): ?string
    {
        return $this->nom;
    }
    public function getProfilepicture()
    {
        return $this->profilepicture;
    }

    public function setprenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function setnom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    public function setProfilepicture($profilepicture)
    {
        $this->profilepicture = $profilepicture;

        return $this;
    }
    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }



    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
   
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\Question;
use App\Entity\User;
use App\Form\UserType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('categorie', ChoiceType::class, [
                'choices' => [
                    'Médecine générale' => 'Médecine générale',
                    'Médecine dentaire' => 'Médecine dentaire',
                    'Pédiatrie' => 'Pédiatrie',
                    'Médecine interne' => 'Médecine interne',
                    'Je ne sais pas' => 'Je ne sais pas',

                ],
                'data_class' => null,

            ])
            ->add('hide_name', CheckboxType::class, [
                'label' => 'Hide Name',
                'required' => false,
                'attr' => [
                    'data-toggle' => 'toggle', // optional: if you want to use Bootstrap Toggle
                ],
            ])

            ->add('question')
            ->add('image', FileType::class, array('data_class' => null), [
                'required' => false, [
                    'mapped' => false
                ]
            ])
            ->add('Confirmer', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

templates/question/_delete_form.html.twig
<form method="post" action="{{ path('app_question_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

templates/question/_form.html.twig
<div class="doc-review review-listing custom-edit-service" bis_skin_checked="1">
	<div class="row mb-5" bis_skin_checked="1">
	<div class="col" bis_skin_checked="1">
	<ul class="nav nav-tabs nav-tabs-solid">
	<li class="nav-item">
	<a class="nav-link" href="doctor-blog.html">Acitive Blog</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="doctor-pending-blog.html">Pending Blog</a>
	</li>
	</ul>
	</div>
	<div class="col-auto" bis_skin_checked="1">
	<a class="btn btn-primary btn-sm" href="doctor-add-blog.html"><i class="fas fa-plus me-1"></i> Add Blog</a>
	</div>
	</div>
	
	<div class="card" bis_skin_checked="1">
	<div class="card-body" bis_skin_checked="1">
	<h3 class="pb-3">Add Blog</h3>
	<form method="post"  action="#">

	<div class="service-fields mb-3" bis_skin_checked="1">
	<div class="row" bis_skin_checked="1">
	<div class="col-lg-6" bis_skin_checked="1">
	<div class="form-group" bis_skin_checked="1">
		{{ form_start(form,{attr:{novalidate:'novalidate'} }) }}
		{{ form_row(form.categorie, {'attr': {'class':'form-control'} }) }}
	</div>
	<div class="col-lg-6" bis_skin_checked="1">
	<div class="form-group" bis_skin_checked="1">
		{{ form_row(form.hide_name, {'attr': {'class':'form-control'} }) }}
	</div>
	</div>
	
	<div class="service-fields mb-3" bis_skin_checked="1">
	<div class="row" bis_skin_checked="1">
	<div class="col-lg-12" bis_skin_checked="1">
	<div class="form-group" bis_skin_checked="1">
		{{ form_row(form.question, {'attr': {'class':'form-control'} }) }}
	</div>
	</div>
	</div>
	</div>
	<div class="service-fields mb-3" bis_skin_checked="1">
	<div class="row" bis_skin_checked="1">
	<div class="col-lg-12" bis_skin_checked="1">
		{{ form_row(form.image, {'attr': {'class':'form-control'} }) }}
	</div>
	</div>
	</div>
	
	<div class="submit-section" bis_skin_checked="1">
		{{ form_row(form.Confirmer, {'attr': {'class':'form-control'} }) }}
	{{ form_end(form) }}
</div>
	</form>
	</div>
	</div>
	
	</div>

templates/question/edit.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Edit Question
{% endblock %}

{% block body %}


		{{ include('question/_form.html.twig') }}

		<a href="{{ path('app_question_index') }}">
			<button>back to list</button>
		</a>

	</div>
{% endblock %}

templates/question/new.html.twig
{% extends 'base1.html.twig' %}

{% block body %}
	

		{{ include('question/_form.html.twig') }}

		
{% endblock %}

templates/question/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Question
{% endblock %}

{% block body %}
<div class="row" style="transform: none;">
		
	<div class="col-md-7 col-lg-8 col-xl-10">
		
			<div
				class="doc-review review-listing">

				<!-- Review Listing -->
				<ul
					class="comments-list">

					<!-- Comment List -->
					<li>
						<a href="{{ path('app_question_edit', {'id': question.id}) }}" style="float: right;color:green;">
							<button class="btn">
								<i class="fas fa-edit"></i>
							</button>
						</a>
						<form method="post" action="{{ path('app_question_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
							<button style="float: right;     color: red;" class="btn" id="delete-button">
								<i class="fas fa-trash-alt"></i>
							</button>
						</form>
						<div class="comment">
							<img class="avatar rounded-circle" alt="User Image" src="{{asset('assets/img/patients/patient1.jpg')}}">
							<div class="comment-body"><a href="{{ path('app_question_show', {'id': question.id}) }}" >
								<div class="meta-data">
									{% if question.gethidename()==1 %}
										<p>Anonymous</p>
									{% else %}
										<p>
											<span class="comment-author">{{ question.getuser().nom }}</span>
										</p>
									{% endif %}

									<span class="comment-date">publié le
										{{ question.getdatepub()|date('d M Y') }}</span>
									</a></div>
								<p class="comment-content">{{ question.question }}</p>
								<p>
									Likes:
									{{ question.likes }}
									<a href="{{ path('Question_like', {'id': question.id}) }}">
										<i class="fa fa-thumbs-up"></i>
									</a>
									Dislikes:
									{{ question.dislikes }}
									<a href="{{ path('Question_dislike', {'id': question.id}) }}">
										<i class="fa fa-thumbs-down"></i>
									</a>
									<a href="{{ path('ssd', {'id': question.id}) }}" title="Share on Facebook" style="
																																																			background-color: #3b5998; color: white; font-weight: bold; padding: 1px; border-radius: 5px; text-decoration: none;">
										Share

									</a>
								</p>

								<div class="comment-response">
									<div class="comment-reply">
										<a class="comment-btn" href="{{ path('app_reponse_new', {'question_id': question.id}) }}">
											<i class="fas fa-response"></i>
											repondre
										</a>
									</div>
									{% for reponse in reponses %}
									{% if reponse.getidquestion() == question.getid() %}
									<div class="card blog-comments clearfix" bis_skin_checked="1">
										

										
											<ul
												class="comments-reply">

												<!-- Comment Reply List -->
												<li>
													<div class="comment">
														<img class="avatar rounded-circle" alt="User Image" src="{{asset('assets1/img/doctors/doctor-thumb-02.jpg')}}">
														<div class="comment-body">
															<div class="meta-data">

																<a href="{{ path('app_reponse_edit', {'id': reponse.id}) }}">
																	<button class="btn">
																		<i style="color:green; position: absolute; top: 0; right: 10px; margin: 20px;" class="fas fa-edit"></i>
																	</button>
																</a>
																<form method="post" action="{{ path('app_reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
																	<input type="hidden" nom="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
																	<button class="btn" id="delete-button">
																		<i style="color:red; position: absolute; top: 0; right: 0; margin: 50px;" class="fas fa-trash-alt"></i>
																	</button>
																</form>
																<span class="comment-author">{{app.user.username}}</span>
																<span class="comment-date">{{reponse.getdatepub()|date('d M Y')}}</span>
															</div>
															<p class="comment-content"></p>
															<p>{{reponse.reponse}}</p>
															<p>
																Likes:
																{{ question.likes }}
																<a href="{{ path('Question_like', {'id': question.id}) }}">
																	<i class="fa fa-thumbs-up"></i>
																</a>
																Dislikes:
																{{ question.dislikes }}
																<a href="{{ path('Question_dislike', {'id': question.id}) }}">
																	<i class="fa fa-thumbs-down"></i>
																</a>
															</p>
														</p>
														<div class="comment-reply">
															<a class="comment-btn" href="{{ path('app_reponse_new', {'question_id': question.id}) }}">
																<i class="fas fa-response"></i>
																repondre
															</a>

														</div>
													</div>
												</li>
											</div>
										</li>
										<!-- /Comment Reply List -->

									</ul>
								</div>
							</div>
							
								{% endif %}
							{% endfor %}
						
						<!-- Replies -->
										</div>
										
										</div>
										</li>
										</ul>
										</div>
										</div>
									
						


<!-- /Comment List -->



	</div><div class="resize-sensor" style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;" bis_skin_checked="1"><div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;" bis_skin_checked="1"><div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 452px; height: 1224px;" bis_skin_checked="1"></div></div><div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;" bis_skin_checked="1"><div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%" bis_skin_checked="1"></div></div></div></div></div>
	
	</div>
	</div>
	</div>









	<h1>Question</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ question.id }}</td>
			</tr>

			<tr>
				<th>Question</th>
				<td>{{ question.question }}</td>
			</tr>
			<tr>
				<th>Date_pub</th>
				<td>{{ question.datePub ? question.datePub|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>likes</th>
				{% if question.likes == NULL %}

					<td>0</td>
				{% else %}
					<td>{{ question.likes}}
						<i style="color:#20d420" class="fa fa-thumbs-up"></i>
					</td>
				{% endif %}
			</tr>
			<tr>
				<th>dislike</th>
				{% if question.Dislikes == NULL %}

					<td>0</td>
				{% else %}
					<td>{{ question.dislikes}}
						<i style="color:red" class="fa fa-thumbs-down"></i>
					</td>
				{% endif %}

			</tr>
			<tr>
				<th>reponse</th>

				<table class="table">
					<thead>
						<tr>
							<th>Id</th>
							<th>Id_user</th>
							<th>Reponse</th>
							<th>Date_pub</th>
							<th>actions</th>
						</tr>
					</thead>
					<tbody>
						{% for reponse in reponses %}
							{% if reponse.getidquestion() == question.getid() %}

								<tr>
									<td>{{ reponse.id }}</td>
									<td>{{ reponse.getuser().nom }}</td>
									<td>{{ reponse.reponse }}</td>
									<td>{{ reponse.datePub ? reponse.datePub|date('Y-m-d') : '' }}</td>
									<td>
										<u1 style="text-align: center;">
											<div class="button-group">
												<a href="{{ path('app_reponse_show', {'id': reponse.id}) }}">
													<button class="btn btn-primary">detail</button>
												</a>
												<form method="post" action="{{ path('app_reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
													<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
													<button class="btn btn-danger delete">Supprimer</button>
												</form>
											</span>
										</u1>
									</td>
								</tr>
							{% endif %}

						{% else %}
							<tr>
								<td colspan="5">pas de question</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</tr>


		</tbody>
	</table>

	<a href="{{ path('app_question_index') }}">back to list</a>

	<a href="{{ path('app_question_edit', {'id': question.id}) }}">edit</a>

	{{ include('question/_delete_form.html.twig') }}
{% endblock %}

templates/question/verif.html.twig
{% extends 'base2.html.twig' %}