src/Entity/Fiche.php
<?php

namespace App\Entity;

use App\Repository\FicheRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FicheRepository::class)]
class Fiche
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\Column(length: 255)]
    private ?string $BloodType = null;

    #[ORM\ManyToOne(inversedBy: 'fiches')]
    private ?User $Patient = null;

    #[ORM\OneToMany(mappedBy: 'fiche', targetEntity: RendezVous::class)]
    private Collection $RendezVous;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $docteur = null;

    public function __construct()
    {
        $this->RendezVous = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getBloodType(): ?string
    {
        return $this->BloodType;
    }

    public function setBloodType(string $BloodType): self
    {
        $this->BloodType = $BloodType;

        return $this;
    }

    public function getPatient(): ?User
    {
        return $this->Patient;
    }

    public function setPatient(?User $Patient): self
    {
        $this->Patient = $Patient;

        return $this;
    }

    /**
     * @return Collection<int, RendezVous>
     */
    public function getRendezVous(): Collection
    {
        return $this->RendezVous;
    }

    public function addRendezVou(RendezVous $rendezVou): self
    {
        if (!$this->RendezVous->contains($rendezVou)) {
            $this->RendezVous->add($rendezVou);
            $rendezVou->setFiche($this);
        }

        return $this;
    }

    public function removeRendezVou(RendezVous $rendezVou): self
    {
        if ($this->RendezVous->removeElement($rendezVou)) {
            // set the owning side to null (unless already changed)
            if ($rendezVou->getFiche() === $this) {
                $rendezVou->setFiche(null);
            }
        }

        return $this;
    }

    public function getDocteur(): ?User
    {
        return $this->docteur;
    }

    public function setDocteur(?User $docteur): self
    {
        $this->docteur = $docteur;

        return $this;
    }
}

src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RendezVousRepository::class)]
class RendezVous
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $Local = null;


    #[ORM\Column(length: 255)]
    private ?string $Statut = null;

    #[ORM\ManyToOne(inversedBy: 'RendezVous')]
    private ?Fiche $fiche = null;

    #[ORM\ManyToOne]
    private ?User $docteur = null;

    #[ORM\ManyToOne(inversedBy: 'rendezVouses')]
    private ?User $patient = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Start = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocal(): ?string
    {
        return $this->Local;
    }

    public function setLocal(string $Local): self
    {
        $this->Local = $Local;

        return $this;
    }





    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getFiche(): ?Fiche
    {
        return $this->fiche;
    }

    public function setFiche(?Fiche $fiche): self
    {
        $this->fiche = $fiche;

        return $this;
    }

    public function getDocteur(): ?User
    {
        return $this->docteur;
    }

    public function setDocteur(?User $docteur): self
    {
        $this->docteur = $docteur;

        return $this;
    }

    public function setPatient(?User $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    public function getPatient(): ?User
    {
        return $this->patient;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->Start;
    }

    public function setStart(\DateTimeInterface $Start): self
    {
        $this->Start = $Start;

        return $this;
    }
}

src/Controller/DocteurController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Fiche;
use App\Entity\RendezVous;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\RendezVousRepository;
use App\Repository\FicheRepository;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\Security;
use App\Form\FicheType;

#[Route('/docteur')]
class DocteurController extends AbstractController
{
    #[Route('/', name: 'app_docteur')]
    public function index(): Response
    {
        return $this->render('docteur/index.html.twig', [
            'controller_name' => 'DocteurController',
        ]);
    }
    #[Route('/register', name: 'app_docteur_register')]
    public function register(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setRoles(['ROLE_DOCTEUR']);
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('app_docteur');
        }

        return $this->render('docteur/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/list', name: 'app_docteur_listRDV')]
    public function listRDV(Security $security, RendezVousRepository $RendezVousRepository): Response
    { {
            if (!$security->isGranted('ROLE_DOCTOR')) {
                return $this->redirectToRoute('app_login');
            }
            $user = $security->getUser();
            return $this->render('bord.html.twig', [
                'RendezVouss' => $RendezVousRepository->findByDocteur($user),
            ]);
        }
    }
    #[Route('/Confirmer/{id}', name: 'Confirmer')]

    public function Confirmer($id, RendezVousRepository $repository)
    {
        //récupérer le RendezVous à supprimer
        $RendezVous = $repository->find($id);
        // $newRendezVous= new RendezVous();

        $RendezVous->setStatut("Confirmé");
        $repository->save($RendezVous, true);
        return $this->redirectToRoute("app_docteur_listRDV");
    }
    #[Route('/Annuler/{id}', name: 'Annuler')]

    public function Annuler($id, RendezVousRepository $repository)
    {
        //récupérer le RendezVous à supprimer
        $RendezVous = $repository->find($id);
        // $newRendezVous= new RendezVous();
        $RendezVous->setStatut("Annulé");

        $repository->save($RendezVous, true);
        return $this->redirectToRoute("app_docteur_listRDV");
    }

    #[Route('/list/fiche', name: 'app_docteur_listFiche')]
    public function listFiche(Security $security, FicheRepository $FicheRepository): Response
    { {
            if (!$security->isGranted('ROLE_DOCTOR')) {
                return $this->redirectToRoute('app_login');
            }
            $user = $security->getUser();

            return $this->render('docteur/listFiche.html.twig', [
                'Fiche' => $FicheRepository->findAll(),
            ]);
        }
    }
    #[Route('/fiche/{id}', name: 'app_docteur_Fiche')]
    public function showFiche(FicheRepository $FicheMedRepository, $id, RendezVousRepository $RendezVousRepository): Response
    {
        return $this->render('docteur/showFiche.html.twig', [
            'Fiche' => $FicheMedRepository->find($id),
            'rendezVous' => $RendezVousRepository->findByFiche($FicheMedRepository->find($id)),
        ]);
    }

    #[Route('/fiche/new/{id}', name: 'app_add_Fiche')]
    public function addFiche(RendezVousRepository $Repository, $id, UserRepository $repo, Security $security, Request $request, EntityManagerInterface $entityManager): Response
    {
        $RendezVous = $Repository->find($id);

        $patient = $RendezVous->getPatient();
        $docteur = $security->getToken()->getUser();


        $Fiche = new Fiche();


        $Fiche->setDocteur($docteur);
        $Fiche->setPatient($patient);


        $form = $this->createForm(FicheType::class, $Fiche);


        $form->handleRequest($request);
        if ($form->isSubmitted()) {


            $entityManager->persist($Fiche);
            $entityManager->flush();
            // $this->sendEmail($mailer,$RendezVous->getPatient()->getEmail());
            // $repository = $entityManager->getRepository(RendezVous::class);


            $RendezVous->setFiche($Fiche);
            $entityManager->persist($RendezVous);
            $entityManager->flush();
            return $this->redirectToRoute('app_docteur_listFiche');
        }
        return $this->render(
            'docteur/newFiche.html.twig',
            [
                'Fiche' => $Fiche,
                'form' => $form->createView()
            ]
        );
    }
}

templates/docteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DocteurController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/user/Desktop/RendezVous/RendezVousProject/src/Controller/DocteurController.php'|file_link(0) }}">src/Controller/DocteurController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/user/Desktop/RendezVous/RendezVousProject/templates/docteur/index.html.twig'|file_link(0) }}">templates/docteur/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/docteur/listFiche.html.twig
{% extends 'bord.html.twig' %}

{% block title %}{% endblock %}

{% block profile %}
	<div
		class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">

		<!-- Profile Sidebar -->
		<div class="profile-sidebar">
			<div class="widget-profile pro-widget-content">
				<div class="profile-info-widget">
					<a href="#" class="booking-doc-img">
						<img src="{{asset ('assets1/img/patients/patient.jpg')}} " alt="User Image">
					</a>
					<div class="profile-det-info">
						<h3>{{app.user.email}}</h3>
						<div class="patient-details">

							<i class="fas fa-map-marker-alt"></i>
							{{app.user.adresse}}</h5>
					</div>

				</div>
			</div>
		</div>
		{% if 'ROLE_PATIENT' in app.user.roles %}


			<div class="dashboard-widget">
				<nav class="dashboard-menu">
					<ul>
						<li>
							<a href="{{path('app_RendezVous')}}">
								<i class="fas fa-columns"></i>
								<span>Tableau de bord</span>
							</a>
						</li>


						<li class="active">
							<a href="{{path ('user_profile')}}">
								<i class="fas fa-user-cog"></i>
								<span>Paramètres de profil</span>
							</a>
						</li>

						<li>
							<a href="doctor-change-password.html">
								<i class="fas fa-lock"></i>
								<span>Changer le mot de passe</span>
							</a>
						</li>
						<li>
							<a href="{{path ('app_logout')}}">
								<i class="fas fa-sign-out-alt"></i>
								<span>Se déconnecter</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		{% elseif 'ROLE_DOCTOR' in app.user.roles %}
			<div class="dashboard-widget">
				<nav class="dashboard-menu">
					<ul>
						<li class="active">
							<a href="{{path ('app_docteur_listFiche')}}">
								<i class="fas fa-columns"></i>
								<span>Fiches</span>
							</a>
						</li>
						<li>
							<a href="{{path ('app_docteur_listRDV')}}">
								<i class="fas fa-calendar-check"></i>
								<span>Rendez-vous</span>
							</a>
						</li>

						<li>
							<a href="Horaires.html">
								<i class="fas fa-hourglass-start"></i>
								<span>Calendrier des horaires</span>
							</a>
						</li>

						<li>
							<a href="{{path ('user_profile')}}">
								<i class="fas fa-user-cog"></i>
								<span>Paramètres de profil</span>
							</a>
						</li>

						<li>
							<a href="doctor-change-password.html">
								<i class="fas fa-lock"></i>
								<span>Changer le mot de passe</span>
							</a>
						</li>
						<li>
							<a href="{{path ('app_logout')}}">
								<i class="fas fa-sign-out-alt"></i>
								<span>Se déconnecter</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		{% elseif 'ROLE_PARA' in app.user.roles %}
			<div class="dashboard-widget">
				<nav class="dashboard-menu">
					<ul>
						<li>
							<a href="doctor-dashboard.html">
								<i class="fas fa-columns"></i>
								<span>Tableau de bord</span>
							</a>
						</li>


						<li class="active">
							<a href="{{path ('user_profile')}}">
								<i class="fas fa-user-cog"></i>
								<span>Paramètres de profil</span>
							</a>
						</li>

						<li>
							<a href="doctor-change-password.html">
								<i class="fas fa-lock"></i>
								<span>Changer le mot de passe</span>
							</a>
						</li>
						<li>
							<a href="{{path ('app_logout')}}">
								<i class="fas fa-sign-out-alt"></i>
								<span>Se déconnecter</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		{% endif %}
	</div>
	<!-- /Profile Sidebar -->

</div>{% endblock %}{% block basic %}


<div class="col-md-7 col-lg-8 col-xl-9">
	<div class="card">
		<div
			class="card-body pt-0">

			<!-- Tab Menu -->
			<nav class="user-tabs mb-4">
				<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
					<li class="nav-item">
						<a class="nav-link active" href="#pat_appointments" data-toggle="tab">Fiches Médicales</a>
					</li>

				</ul>
			</nav>
			<!-- /Tab Menu -->

			<!-- Tab Content -->
			<div
				class="tab-content pt-0">

				<!-- Appointment Tab -->
				<div id="pat_appointments" class="tab-pane fade active show">
					<div class="card card-table mb-0">
						<div class="card-body">
							<div class="table-responsive">
								<table class="table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>Patient</th>
											<th>Age</th>
											<th>bloodType</th>
											<th>Action</th>


										</tr>
									</thead>
									<tbody>
										{% for Fich in Fiche %}
											<tr>
												<td>
													<h2 class="table-avatar">

														<a href="{{ path('app_docteur_Fiche', {'id': Fich.id}) }}">{{ Fich.patient.nom }}

														</h2>
													</td>
												</td>
												<td>{{ Fich.age}}</td>
												<td>{{ Fich.bloodType}}</td>
												<td>
													<a class="btn btn-primary" href="#">Print To PDF</a>
												</td>


											</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<!-- /Appointment Tab -->


			</div>
			<!-- Tab Content -->

		</div>


	</div>
</div></div>{% endblock %}{%block Sidebar%}<!-- Sidebar --><div class="sidebar" id="sidebar"><div class="sidebar-inner slimscroll">
<div id="sidebar-menu" class="sidebar-menu">
	<ul>
		<li class="menu-title">
			<span>Main</span>
		</li>
		<li>
			<a href="index.html">
				<i class="fe fe-home"></i>
				<span>Tableau de bord</span>
			</a>
		</li>
		<li>
			<a href="{{ path('app_docteur_listRDV') }}">
				<i class="fe fe-layout"></i>
				<span>Rendez-vous</span>
			</a>
		</li>
		<li class="active">
			<a href="{{ path('app_docteur_listFiche') }}">
				<i class="fe fe-users"></i>
				<span>Fiche Médicale</span>
			</a>
		</li>
		<li>
			<a href="doctor-list.html">
				<i class="fe fe-user-plus"></i>
				<span>Doctors</span>
			</a>
		</li>
		<li>
			<a href="patient-list.html">
				<i class="fe fe-user"></i>
				<span>Patients</span>
			</a>
		</li>
		<li>
			<a href="para-list.html">
				<i class="fe fe-user"></i>
				<span>parapharmacie
				</span>
			</a>
		</li>
		<li>
			<a href="Forum.html">
				<i class="fe fe-star-o"></i>
				<span>Forum</span>
			</a>
		</li>
		<li>
			<a href="reclamation.html">
				<i class="fe fe-file"></i>
				<span>Reclamation</span>
			</a>
		</li>

		<li>
			<a href="profile.html">
				<i class="fe fe-user-plus"></i>
				<span>Profile</span>
			</a>
		</li>

	</ul>
</div></div></div><!-- /Sidebar -->{%endblock%}{% block breadcrumb %}<!-- Breadcrumb --><div class="breadcrumb-bar">
<div class="container-fluid">
	<div class="row align-items-center">
		<div class="col-md-12 col-12">
			<nav aria-label="breadcrumb" class="page-breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="index-2.html">Home</a>
					</li>
					<li class="breadcrumb-item active" aria-current="page">Appointments</li>
				</ol>
			</nav>
			<h2 class="breadcrumb-title">Appointments</h2>
		</div>
	</div>
</div></div>{% endblock %}

templates/docteur/newFiche1.html.twig
{% extends 'base1.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
{%endblock%}

templates/docteur/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
    <h1>Register</h1>

    {{ form_start(registrationForm) }}
        {{ form_row(registrationForm.email) }}
        {{ form_row(registrationForm.plainPassword, {
            label: 'Password'
        }) }}
        {{ form_row(registrationForm.agreeTerms) }}

        <button type="submit" class="btn">Register</button>
    {{ form_end(registrationForm) }}
{% endblock %}

templates/docteur/showFiche.html.twig
{% extends 'bord.html.twig' %}

{% block title %}{% endblock %}

{% block basic %}
	<div class="col-md-7 col-lg-8 col-xl-9">
		<div class="card">
			<div class="content" style="transform: none; min-height: 68.7px;">
				<div class="container-fluid" style="transform: none;">

					<div class="row" style="transform: none;">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar dct-dashbd-lft" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">


							<div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; top: 0px; left: 30px;">
								<div class="card widget-profile pat-widget-profile">

									<div class="card flex-fill" style="display:flex; align-items:center; justify-content:center;">
										<div class="avatar avatar-xl">
											<img class="avatar-img rounded-circle" alt="User Image" src="{{asset('assets/img/profiles/avatar-02.jpg')}}">
										</div>

										<div class="card-header">
											<h5 class="card-title mb-0">{{Fiche.patient.nom}}</h5>
										</div>
										<div class="card-body">
											<p class="card-text">ID:
												{{Fiche.id}}</p>
											<p class="card-text">Age:
												{{Fiche.Age}}</p>
											<p class="card-text">Groupe Sanguin:
												{{Fiche.bloodType}}</p>
											<a class="btn btn-primary" href="#">Print To PDF</a>
										</div>
									</div>
								</div>
								<div class="resize-sensor" style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;">
									<div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
										<div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 408px; height: 1002px;"></div>
									</div>
									<div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
										<div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div>
									</div>
								</div>
							</div>
						</div>

						<div class="col-md-7 col-lg-8 col-xl-9 dct-appoinment">
							<div class="card">
								<div class="card-body pt-0">
									<div class="user-tabs">
										<ul class="nav nav-tabs nav-tabs-bottom nav-justified flex-wrap">
											<li class="nav-item">
												<a class="nav-link active" href="#pat_appointments" data-toggle="tab">Appointments</a>
											</li>


										</ul>
									</div>
									<div
										class="tab-content">

										<!-- Appointment Tab -->
										<div id="pat_appointments" class="tab-pane fade active show">
											<div class="card card-table mb-0">
												<div class="card-body">
													<div class="table-responsive">
														<table class="table table-hover table-center mb-0">
															<thead>
																<tr>

																	<th>Appt Date</th>
																	<th>Status</th>
																	<th>Local</th>

																</tr>
															</thead>
															<tbody>
																{% for RendezVous in rendezVous %}
																	<tr>


																		<td>{{ RendezVous.date|date('Y-m-d H:i:s') }}</td>
																		{% if RendezVous.statut=='Pending' %}
																			<td>
																				<span class="badge badge-pill bg-warning-light">{{ RendezVous.statut}}</span>
																			{% endif %}
																			{% if RendezVous.statut=='Confirmé' %}
																				<td>
																					<span class="badge badge-pill bg-success-light">{{ RendezVous.statut}}</span>

																				{% endif %}
																				{% if RendezVous.statut=='Annulé' %}
																					<td>
																						<span class="badge badge-pill bg-danger-light">{{ RendezVous.statut}}</span>
																					{% endif %}
																				</td>
																				<td>{{ RendezVous.Local}}</td>
																			</tr>

																		{% endfor %}
																	</tr>
																</tbody>
															</tbody>
														</table>
													</div>
												</div>
											</div>
										</div>
										<!-- /Appointment Tab -->


									</div>
								</div>
							</div>
						</div>
					</div>

				</div>

			</div>
		</div>
	</div>

{% endblock %}

{% block breadcrumb %}
	<!-- Breadcrumb -->
	<div class="breadcrumb-bar">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-12 col-12">
					<nav aria-label="breadcrumb" class="page-breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item">
								<a href="index-2.html">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Appointments</li>
						</ol>
					</nav>
					<h2 class="breadcrumb-title">Appointments</h2>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{%block Sidebar%}
<!-- Sidebar -->
<div class="sidebar" id="sidebar">
	<div class="sidebar-inner slimscroll">
		<div id="sidebar-menu" class="sidebar-menu">
			<ul>
				<li class="menu-title">
					<span>Main</span>
				</li>
				<li>
					<a href="index.html">
						<i class="fe fe-home"></i>
						<span>Tableau de bord</span>
					</a>
				</li>
				<li>
					<a href="{{ path('app_docteur_listRDV') }}">
						<i class="fe fe-layout"></i>
						<span>Rendez-vous</span>
					</a>
				</li>
				<li class="active">
					<a href="{{ path('app_docteur_listFiche') }}">
						<i class="fe fe-users"></i>
						<span>Fiche Médicale</span>
					</a>
				</li>
				<li>
					<a href="doctor-list.html">
						<i class="fe fe-user-plus"></i>
						<span>Doctors</span>
					</a>
				</li>
				<li>
					<a href="patient-list.html">
						<i class="fe fe-user"></i>
						<span>Patients</span>
					</a>
				</li>
				<li>
					<a href="para-list.html">
						<i class="fe fe-user"></i>
						<span>parapharmacie
						</span>
					</a>
				</li>
				<li>
					<a href="Forum.html">
						<i class="fe fe-star-o"></i>
						<span>Forum</span>
					</a>
				</li>
				<li>
					<a href="reclamation.html">
						<i class="fe fe-file"></i>
						<span>Reclamation</span>
					</a>
				</li>

				<li>
					<a href="profile.html">
						<i class="fe fe-user-plus"></i>
						<span>Profile</span>
					</a>
				</li>

			</ul>
		</div>
	</div>
</div>
<!-- /Sidebar -->
{%endblock%}